### ISSUE TITLE
HttpClientFactory

### ISSUE THREAD

**Issue by grahamehorner** [anthonychu/AzureAdvocates.WebJobs.Extensions.SignalRService#4]
Please consider using HttpClientFactory extensions with transient error handling, retry and backoff policy

**Comment by anthonychu** [comment]
Thanks. We have an updated version that uses HttpClientFactory. In the process of migrating this project to a repo on the Azure GitHub org. Should be available soon.

**Comment by anthonychu** [comment]
New repo is now live. Thanks.

https://github.com/Azure/azure-functions-signalrservice-extension
