### ISSUE TITLE
Problem when running under new AF runtime 2.0.12050.0

### ISSUE THREAD

**Issue by eiximenis** [anthonychu/AzureAdvocates.WebJobs.Extensions.SignalRService#5]
Hi!

I am using `AzureAdvocates.WebJobs.Extensions.SignalRService:0.2.0-alpha`  to run AF under the [new runtime released 2.0.12050.0](https://github.com/Azure/app-service-announcements/issues/129). This runtime is used by the new AzureFunctionTools 2.5.1 automatically downloaded by VS 15.9 Preview 1.

Signature of my both AF is:

```
public static async Task Run([BlobTrigger("stuff/{name}", Connection = "blobconstr")]Stream myBlob,
    [SignalR(HubName = "fileprocess", ConnectionStringSetting = "signalrconstr")] IAsyncCollector<SignalRMessage> sender,
    string name, ILogger log)
```

```
public static IActionResult SignalRInfo(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post")]HttpRequestMessage req,
    [SignalRConnectionInfo(HubName = "fileprocess")]AzureSignalRConnectionInfo info, ILogger logger)
```

I upgraded the project to use new `Microsoft.NET.Sdk.Functions:1.0.19`. No nuget conflicts:

![image](https://user-images.githubusercontent.com/5191049/44910092-31280600-ad22-11e8-8b1e-21fec04adbc9.png)

When I start the project locally using VS, I get two errors (one per function) related to the SignalR bindings:

```
[31-Aug-18 11:32:39 AM] Microsoft.Azure.WebJobs.Host: Error indexing method 'SignalRDemoFunctions.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'sender' to type IAsyncCollector`1. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

[31-Aug-18 11:32:39 AM] Error indexing method 'SignalRDemoFunctions.SignalRInfo'
[31-Aug-18 11:32:39 AM] Microsoft.Azure.WebJobs.Host: Error indexing method 'SignalRDemoFunctions.SignalRInfo'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'info' to type AzureSignalRConnectionInfo. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
```

I have been looking your sample trivia app but can't see any relevant difference.

Is current version of the package compatible with new AF runtime 2.0.12050.0 or I am doing something wrong? If current version is not compatible is there any ETA for a compatible version?

Thanks!

**Comment by Liteolika** [comment]
I created a PR #6  to resolve the issue.

**Comment by anthonychu** [comment]
Thanks all, especially @Liteolika for submitting a PR to fix this. We have a new version ready that we haven't pushed to GitHub, as we're in the process of moving this extension into the official Azure org on GitHub and NuGet. I've published that version under the current package name on NuGet, it should be live soon.

**Comment by anthonychu** [comment]
Looks like it is now live. Please update to 0.3.0-alpha to use it with the updated runtime.

https://www.nuget.org/packages/AzureAdvocates.WebJobs.Extensions.SignalRService/0.3.0-alpha

**Comment by eiximenis** [comment]
Works like a charm! 

For anything following the samples, just beware that in 0.3.0-alpha the class `AzureSignalRConnectionInfo` has been renamed to `SignalRConnectionInfo`

Thanks!

**Comment by mercenaryntx** [comment]
"Works like a charm!"

Wish I could say the same. :(
With this fix you also upgraded the Microsoft.Azure.WebJobs dependency from 3.0.0-beta5 to 3.0.0-beta8 which is a buggy one. (https://github.com/Azure/Azure-Functions/issues/950)

So I cannot use neither of the available NuGet package, aaaaand because you haven't pushed the recent changes to GitHub I cannot even fix it for myself. :/
So could you please update Microsoft.Azure.WebJobs to 3.0.0-rc1 ASAP?

Thank you!

**Comment by anthonychu** [comment]
@mercenaryntx Please use https://github.com/Azure/azure-functions-signalrservice-extension . It's up to date and will work with the latest extensions.
