### ISSUE TITLE
Webjobs extensibility model changed

### ISSUE THREAD

**Issue by cschrammel** [anthonychu/AzureAdvocates.WebJobs.Extensions.SignalRService#7]
It seems that with the latest version of Microsoft.NET.Sdk.Functions, the webjobs extensibility model changed and this package currently does not work.  Do you have any plans to upgrade this to support the latest model?

Thanks!

**Comment by JontyMC** [comment]
:thumbsup:

**Comment by anthonychu** [comment]
This has been fixed in a new version. Please see the new official repo here:
https://github.com/Azure/azure-functions-signalrservice-extension

Thanks!
